### ISSUE TITLE
External Videos

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bbb-playback#77] opened 2020-10-26 19:41 UTC
Hi,

we are using your code to playback BBB recordings. We prefer it to default playback. I would like to ask you if you think that external videos can be considered in you develop. I know that you can't record it but I would like to ask you that if we create new events in event.xml file asociated to external videos (for example the video URL, and if the moderator start/stop the video), you think that you could reproduce them. I mean that instead of record external videos, that your bbb-playback reproduce external videos in similar way that in a meeting is done.

Thank you very much.
Regards

**Comment by pedrobmarin** [comment] 2020-10-26 19:54
Hi @amguirado73 ,

We mapped this up here #17 but syncing everything will be tough. I would probably need a full week focused on this and right now I can't find that time. But definitely is something to be done.

I'll close this one since is a duplicate of #17 and you can follow any progressions there.

**Closed by pedrobmarin** 2020-10-26 19:54 UTC
Labels: duplicate

**Comment by amguirado73** [comment] 2020-10-26 19:59
Hi,

thank you very much.

Regards
